# NumPy Arrays:

In [1]:
import numpy as np

In [2]:
my_list=[1,2,3]

In [3]:
my_list

[1, 2, 3]

In [5]:
arr=np.array(my_list)

In [8]:
arr

array([1, 2, 3])

In [9]:
my_matrix =([1,2,3],[4,5,6],[7,8,9])

In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.linspace(0,10,25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.random.rand(3)

array([0.8617135 , 0.11594411, 0.34994301])

In [24]:
np.random.randn(3)

array([-1.14242417,  0.89249651,  0.28737661])

In [25]:
arr=np.arange(25)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
rarr=np.random.randint(0,50,10)

In [30]:
rarr

array([ 8, 49, 16, 24, 22, 23, 26, 45,  7, 46])

In [33]:
rarr.min()

7

In [34]:
rarr.max()

49

In [35]:
rarr.argmin()

8

In [36]:
rarr.argmax()

1

In [37]:
rarr.dtype

dtype('int32')

In [38]:
arr.dtype

dtype('int32')

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
arr[15]

15

In [49]:
# Trying to slice the array
slice=arr[1:5]

In [50]:
slice

array([100, 100, 100,   4])

In [51]:
# Changes are reflected in the main array arr too
arr

array([  0, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [42]:
arr[22:]

array([22, 23, 24])

In [44]:
arr[1:4]=100

In [45]:
arr

array([  0, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [53]:
arr

array([  0, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [54]:
np.array(arr)

array([  0, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [57]:
arr.reshape(5,5)

array([[  0, 100, 100, 100,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24]])

In [63]:
arr[5]

5

In [66]:
arr1=np.array(([1,4,5],[2,6,8],[10,19,18]))

In [67]:
arr1

array([[ 1,  4,  5],
       [ 2,  6,  8],
       [10, 19, 18]])

In [70]:
arr1[0][1]

4

In [72]:
arr1[1:,1:]

array([[ 6,  8],
       [19, 18]])

In [74]:
x=np.zeros((10,10))

In [75]:
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [76]:
x.shape[1]

10

In [77]:
x[[2,4,6,8]]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [81]:
arr2=np.arange(1,11)

In [82]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
arr2 >4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [88]:
arr=np.arange(0,11)

In [89]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [91]:
arr/arr

C:\Users\priya\AppData\Local\Temp\ipykernel_25624\1862401812.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [94]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

# Exercise Practise:

In [93]:
import numpy as np

In [95]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [96]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [105]:
ap=np.arange(10,51)

In [106]:
ap

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [108]:
ap1=np.arange(10,51,2)

In [109]:
ap1

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [110]:
ay=np.array(([0,1,2],[3,4,5],[6,7,8]))

In [111]:
ay

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [112]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [126]:
np.random.rand(1)

array([0.86545146])

In [185]:
np.random.randn(25)

array([-0.7047595 ,  0.73137894, -1.01376437,  1.38106278, -0.20330238,
        0.85533296,  1.32485363,  0.8729622 , -0.76713007,  0.79434723,
       -0.20034465,  1.29830444,  0.20085958, -0.71018416, -0.09159985,
       -1.93217315, -1.37616345,  1.46639837, -0.25609983,  0.22247725,
       -0.84767913,  1.67963705,  0.14281103, -1.97378246,  0.16136418])

In [189]:
np.arange(0.01,1,0.01)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99])

In [149]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [154]:
mat=np.arange(1,26).reshape(5,5)

In [155]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [156]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [158]:
mat[3][4]

20

In [172]:
mat[:3,1]

array([ 2,  7, 12])

In [173]:
mat[4]

array([21, 22, 23, 24, 25])

In [174]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [175]:
mat+mat

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

In [179]:
np.sum(mat)

325

In [182]:
np.std(mat)

7.211102550927978

In [191]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])